language: python
python:
  - '3.6'

before_script:
  - pip install -r ./PurBeurre/requirements.txt

branches:
  only:
    - staging  

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - python manage.py test
