language: python
python:
  - '3.6'

before_script:
  - pip install -r ./PurBeurre/requirements.txt
  - source env/bin/activate

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - python ./PurBeurre/manage.py test
